#############################################################################
# Makefile for building: koalatweet
# Generated by qmake (2.01a) (Qt 4.5.0) on: Fri Feb 12 13:09:24 2010
# Project:  koalatweet.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile koalatweet.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtWebKit -I/usr/include/qt4 -I. -Isrc/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtWebKit -lQtGui -lQtNetwork -lQtCore -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/source/apitwitter.cpp \
		src/source/Connection.cpp \
		src/source/ExceptionTweet.cpp \
		src/source/HttpRequest.cpp \
		src/source/HttpResponse.cpp \
		src/source/login.cpp \
		src/source/main.cpp \
		src/source/mainwindow.cpp \
		src/source/network.cpp \
		src/source/ParseCommon.cpp \
		src/source/ParseHttp.cpp \
		src/source/ParseJson.cpp \
		src/source/Status.cpp \
		src/source/User.cpp moc_login.cpp \
		moc_mainwindow.cpp
OBJECTS       = apitwitter.o \
		Connection.o \
		ExceptionTweet.o \
		HttpRequest.o \
		HttpResponse.o \
		login.o \
		main.o \
		mainwindow.o \
		network.o \
		ParseCommon.o \
		ParseHttp.o \
		ParseJson.o \
		Status.o \
		User.o \
		moc_login.o \
		moc_mainwindow.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		koalatweet.pro
QMAKE_TARGET  = koalatweet
DESTDIR       = 
TARGET        = koalatweet

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_login.h ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: koalatweet.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/libQtWebKit.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtNetwork.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile koalatweet.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/libQtWebKit.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtNetwork.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile koalatweet.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/koalatweet1.0.0 || $(MKDIR) .tmp/koalatweet1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/koalatweet1.0.0/ && $(COPY_FILE) --parents src/include/apitwitter.h src/include/Connection.h src/include/ExceptionTweet.h src/include/HttpRequest.h src/include/HttpResponse.h src/include/login.h src/include/mainwindow.h src/include/network.h src/include/ParseCommon.h src/include/ParseHttp.h src/include/ParseJson.h src/include/Status.h src/include/User.h .tmp/koalatweet1.0.0/ && $(COPY_FILE) --parents src/source/apitwitter.cpp src/source/Connection.cpp src/source/ExceptionTweet.cpp src/source/HttpRequest.cpp src/source/HttpResponse.cpp src/source/login.cpp src/source/main.cpp src/source/mainwindow.cpp src/source/network.cpp src/source/ParseCommon.cpp src/source/ParseHttp.cpp src/source/ParseJson.cpp src/source/Status.cpp src/source/User.cpp .tmp/koalatweet1.0.0/ && $(COPY_FILE) --parents src/forms/login.ui src/forms/mainwindow.ui .tmp/koalatweet1.0.0/ && (cd `dirname .tmp/koalatweet1.0.0` && $(TAR) koalatweet1.0.0.tar koalatweet1.0.0 && $(COMPRESS) koalatweet1.0.0.tar) && $(MOVE) `dirname .tmp/koalatweet1.0.0`/koalatweet1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/koalatweet1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_login.cpp moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_login.cpp moc_mainwindow.cpp
moc_login.cpp: ui_login.h \
		src/include/login.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/include/login.h -o moc_login.cpp

moc_mainwindow.cpp: src/include/login.h \
		ui_login.h \
		src/include/network.h \
		src/include/apitwitter.h \
		src/include/Connection.h \
		src/include/mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/include/mainwindow.h -o moc_mainwindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_login.h ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_login.h ui_mainwindow.h
ui_login.h: src/forms/login.ui
	/usr/bin/uic-qt4 src/forms/login.ui -o ui_login.h

ui_mainwindow.h: src/forms/mainwindow.ui
	/usr/bin/uic-qt4 src/forms/mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

apitwitter.o: src/source/apitwitter.cpp src/include/apitwitter.h \
		src/include/mainwindow.h \
		src/include/login.h \
		ui_login.h \
		src/include/network.h \
		src/include/Connection.h \
		src/include/HttpRequest.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o apitwitter.o src/source/apitwitter.cpp

Connection.o: src/source/Connection.cpp src/include/Connection.h \
		src/include/mainwindow.h \
		src/include/login.h \
		ui_login.h \
		src/include/network.h \
		src/include/apitwitter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Connection.o src/source/Connection.cpp

ExceptionTweet.o: src/source/ExceptionTweet.cpp src/include/ExceptionTweet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ExceptionTweet.o src/source/ExceptionTweet.cpp

HttpRequest.o: src/source/HttpRequest.cpp src/include/HttpRequest.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HttpRequest.o src/source/HttpRequest.cpp

HttpResponse.o: src/source/HttpResponse.cpp src/include/HttpResponse.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HttpResponse.o src/source/HttpResponse.cpp

login.o: src/source/login.cpp src/include/login.h \
		ui_login.h \
		src/include/mainwindow.h \
		src/include/network.h \
		src/include/apitwitter.h \
		src/include/Connection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o login.o src/source/login.cpp

main.o: src/source/main.cpp src/include/mainwindow.h \
		src/include/login.h \
		ui_login.h \
		src/include/network.h \
		src/include/apitwitter.h \
		src/include/Connection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/source/main.cpp

mainwindow.o: src/source/mainwindow.cpp src/include/mainwindow.h \
		src/include/login.h \
		ui_login.h \
		src/include/network.h \
		src/include/apitwitter.h \
		src/include/Connection.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o src/source/mainwindow.cpp

network.o: src/source/network.cpp src/include/network.h \
		src/include/mainwindow.h \
		src/include/login.h \
		ui_login.h \
		src/include/apitwitter.h \
		src/include/Connection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o network.o src/source/network.cpp

ParseCommon.o: src/source/ParseCommon.cpp src/include/ParseCommon.h \
		src/include/ExceptionTweet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ParseCommon.o src/source/ParseCommon.cpp

ParseHttp.o: src/source/ParseHttp.cpp src/include/ParseHttp.h \
		src/include/ParseCommon.h \
		src/include/ExceptionTweet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ParseHttp.o src/source/ParseHttp.cpp

ParseJson.o: src/source/ParseJson.cpp src/include/ParseJson.h \
		src/include/ParseCommon.h \
		src/include/ExceptionTweet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ParseJson.o src/source/ParseJson.cpp

Status.o: src/source/Status.cpp src/include/Status.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Status.o src/source/Status.cpp

User.o: src/source/User.cpp src/include/User.h \
		src/include/Status.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o User.o src/source/User.cpp

moc_login.o: moc_login.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_login.o moc_login.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

